### ISSUE TITLE
Adding a license to the repo?

### ISSUE THREAD

**Issue by hr-oss** [krasi070/GameOff2022#1]
Howdy!

This game is so awesome😄 I was curious, if you’d like to add a license to the repo? That way people don’t have to worry about getting sued if they use it :P 

Here’s a tutorial on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you and have a great day :D

**Comment by krasi070** [comment]
Done :)

Thanks for checking out the game and the source!
